/**
 * Rebuild src/assets/icons.js and src/assets/legend-modern.js from the
 * copied SVG files. Run: node scripts/build-icons.js
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

function read(rel) {
  return fs.readFileSync(path.join(root, rel), 'utf8');
}

function write(rel, text) {
  fs.writeFileSync(path.join(root, rel), text);
}

function buildIcons() {
  const dir = path.join(root, 'src/assets/icons');
  const files = fs.readdirSync(dir).filter((name) => name.endsWith('.svg')).sort();
  const lines = files.map((name) => {
    const id = name.slice(0, -4);
    let svg = fs.readFileSync(path.join(dir, name), 'utf8').trim();
    if (!svg.includes('aria-hidden')) svg = svg.replace('<svg ', '<svg aria-hidden="true" ');
    if (!svg.includes('stroke="currentColor"')) svg = svg.replace('<svg ', '<svg stroke="currentColor" ');
    if (!svg.includes('fill="none"')) svg = svg.replace('<svg ', '<svg fill="none" ');
    return `  ${JSON.stringify(id)}: ${JSON.stringify(svg)},`;
  });
  write('src/assets/icons.js', `/** Generated by scripts/build-icons.js. Do not edit by hand. */\nexport const ICONS = {\n${lines.join('\n')}\n};\n`);
}

function innerMarkup(svg) {
  return svg.replace(/^[\s\S]*?<svg\b[^>]*>/, '').replace(/<\/svg>\s*$/, '').trim();
}

function buildLegend() {
  const dir = path.join(root, 'src/assets/legend-modern');
  const index = JSON.parse(read('src/assets/legend-modern/index.json'));
  const lines = index.map((row) => {
    const file = path.join(dir, path.basename(row.file));
    const svg = fs.readFileSync(file, 'utf8').trim();
    const viewBox = (svg.match(/viewBox="([^"]+)"/) || [])[1] || '0 0 1 1';
    const entry = {
      w: row.w,
      d: row.d,
      viewBox,
      inner: innerMarkup(svg),
    };
    return `  ${JSON.stringify(row.id)}: ${JSON.stringify(entry)},`;
  });
  write('src/assets/legend-modern.js', `/** Generated by scripts/build-icons.js. Do not edit by hand. */\nexport const LEGENDS = {\n${lines.join('\n')}\n};\n`);
}

buildIcons();
buildLegend();
console.log('built icons and legend modules');
